server:
  port: 7003
#Eureka 配置
eureka:  instance:    hostname: eureka7003.com #首先声明eureka服务端名字
  client:    register-with-eureka: false #是否向eureka中心注册自己
    fetch-registry: false #如果fetch-registry为false，则表示自己是注册中心
    service-url: #监控页面
      #使用${}动态获取yml配置文件中值
      #defaultZone 默认http://localhost:8761/eureka      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
